from __future__ import annotations

import argparse
from pathlib import Path

from land_change_detection.cluster import YSUClusterLayout, ensure_directory, ensure_symlink


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Prepare the YSU cluster workspace layout for Land-Change-Detection.")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--cluster-user", default="svardanyan")
    parser.add_argument("--project-slug", default="land-change-detection")
    parser.add_argument("--weka-base", type=Path, default=None)
    parser.add_argument("--home-base", type=Path, default=None)
    parser.add_argument("--conda-env-name", default="lcd")
    parser.add_argument("--symlink", action="store_true", help="Create repo-root data/artifacts symlinks into Weka.")
    parser.add_argument("--force", action="store_true", help="Replace conflicting symlinks.")
    parser.add_argument("--write-env-file", type=Path, default=None, help="Write reusable shell exports to this path.")
    return parser


def _render_env_file(layout: YSUClusterLayout) -> str:
    lines = ["# Generated by scripts/prepare_ysu_cluster.py"]
    for key, value in layout.shell_exports().items():
        lines.append(f'export {key}="{value}"')
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    layout = YSUClusterLayout(
        repo_root=args.repo_root.resolve(),
        cluster_user=args.cluster_user,
        project_slug=args.project_slug,
        weka_base=args.weka_base,
        home_base=args.home_base,
        conda_env_name=args.conda_env_name,
    )

    for directory in layout.managed_directories():
        ensure_directory(directory)
        print(f"mkdir_ok {directory}")

    if args.symlink:
        for link_path, target_path in layout.symlink_pairs():
            ensure_symlink(link_path, target_path, force=args.force)
            print(f"symlink_ok {link_path} -> {target_path}")

    if args.write_env_file is not None:
        args.write_env_file.parent.mkdir(parents=True, exist_ok=True)
        args.write_env_file.write_text(_render_env_file(layout))
        print(f"env_file_ok {args.write_env_file}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
